version: '3.8'
services:

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=Asia/Manila
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql:Z

  crabfarmbackend:
    image: crabfarm-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "0.0.0.0:4572:4572"
    # volumes:
    #   - .:/app:Z
    depends_on:
      - mysql
    command: uvicorn App:app --host 0.0.0.0 --port 4572
    restart: always
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: crabfarm-database
      DB_USERNAME: root
      DB_PASSWORD: ""
    env_file:
      - .env

volumes:
  mysql_data: