services:
  crabfarmbackend:
    image: crabfarmbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4572:4572
      
    environment:
      DB_CONNECTION: mysql
      DB_HOST: host.docker.internal   # Connect to your local XAMPP MySQL
      DB_PORT: 3306
      DB_DATABASE: crabfarm-database
      DB_USERNAME: root               # Adjust if your XAMPP MySQL has a password
      DB_PASSWORD: ""

    env_file:
      - .env
