"""update_schema

Revision ID: 3b6a664a5903
Revises: 42e606fb8efe
Create Date: 2026-07-26 15:16:52.360283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3b6a664a5903'
down_revision: Union[str, Sequence[str], None] = '42e606fb8efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_crab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_crab_id'), 'batch_crab', ['id'], unique=False)
    op.create_index(op.f('ix_batch_crab_user_id'), 'batch_crab', ['user_id'], unique=False)
    op.drop_index(op.f('ix_calibration_settings_calibration_type'), table_name='calibration_settings')
    op.drop_index(op.f('ix_calibration_settings_id'), table_name='calibration_settings')
    op.drop_table('calibration_settings')
    op.add_column('activity_logs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('activity_logs', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               nullable=True)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.alter_column('chat_messages', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               type_=sa.Enum('user', 'assistant', name='chat_role_enum'),
               existing_nullable=False)
    op.drop_index(op.f('client_message_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'client_message_id')
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.alter_column('crab', 'group_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.add_column('crab_logs', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.add_column('crab_logs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('crab_logs', 'crab_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('crab_logs', 'width',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('crab_logs', 'weight',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.create_index(op.f('ix_crab_logs_batch_id'), 'crab_logs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_crab_logs_user_id'), 'crab_logs', ['user_id'], unique=False)
    op.add_column('scheduler_settings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_scheduler_settings_user_id'), 'scheduler_settings', ['user_id'], unique=False)
    op.drop_column('scheduler_settings', 'last_run')
    op.drop_column('scheduler_settings', 'created_by')
    op.alter_column('sensor_logs', 'status',
               existing_type=mysql.ENUM('NORMAL', 'WARNING', 'DANGER', collation='utf8mb4_general_ci'),
               nullable=True)
    op.drop_index(op.f('idx_sensor_logs_status'), table_name='sensor_logs')
    op.drop_index(op.f('idx_sensor_logs_type'), table_name='sensor_logs')
    op.add_column('users', sa.Column('role', sa.String(length=6), nullable=False))
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               type_=sa.String(length=254),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('users', 'pin',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False))
    op.alter_column('users', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'pin',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=254),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               existing_nullable=False)
    op.drop_column('users', 'role')
    op.create_index(op.f('idx_sensor_logs_type'), 'sensor_logs', ['sensor_type'], unique=False)
    op.create_index(op.f('idx_sensor_logs_status'), 'sensor_logs', ['status'], unique=False)
    op.alter_column('sensor_logs', 'status',
               existing_type=mysql.ENUM('NORMAL', 'WARNING', 'DANGER', collation='utf8mb4_general_ci'),
               nullable=False)
    op.add_column('scheduler_settings', sa.Column('created_by', mysql.VARCHAR(collation='utf8mb4_general_ci', length=150), nullable=False))
    op.add_column('scheduler_settings', sa.Column('last_run', mysql.TIMESTAMP(), nullable=True))
    op.drop_index(op.f('ix_scheduler_settings_user_id'), table_name='scheduler_settings')
    op.drop_column('scheduler_settings', 'user_id')
    op.drop_index(op.f('ix_crab_logs_user_id'), table_name='crab_logs')
    op.drop_index(op.f('ix_crab_logs_batch_id'), table_name='crab_logs')
    op.alter_column('crab_logs', 'weight',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('crab_logs', 'width',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('crab_logs', 'crab_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('crab_logs', 'user_id')
    op.drop_column('crab_logs', 'batch_id')
    op.alter_column('crab', 'group_by',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.add_column('chat_messages', sa.Column('client_message_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True))
    op.create_index(op.f('client_message_id'), 'chat_messages', ['client_message_id'], unique=True)
    op.alter_column('chat_messages', 'role',
               existing_type=sa.Enum('user', 'assistant', name='chat_role_enum'),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.alter_column('activity_logs', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               nullable=False)
    op.drop_column('activity_logs', 'user_id')
    op.create_table('calibration_settings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('calibration_type', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('value', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_by', mysql.VARCHAR(collation='utf8mb4_general_ci', length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_calibration_settings_id'), 'calibration_settings', ['id'], unique=False)
    op.create_index(op.f('ix_calibration_settings_calibration_type'), 'calibration_settings', ['calibration_type'], unique=True)
    op.drop_index(op.f('ix_batch_crab_user_id'), table_name='batch_crab')
    op.drop_index(op.f('ix_batch_crab_id'), table_name='batch_crab')
    op.drop_table('batch_crab')
    # ### end Alembic commands ###
