"""activity logs tables

Revision ID: aefb5bbab48e
Revises: 33e05a5b7d66
Create Date: 2026-05-03 15:17:16.997418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aefb5bbab48e'
down_revision: Union[str, Sequence[str], None] = '33e05a5b7d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('sensors', 'auth', 'crab_logs', 'scheduler', name='activity_logs_enum'), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_logs_id', 'activity_logs', ['id'], unique=False)
    op.create_index('idx_activity_logs_type', 'activity_logs', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.add_column('scheduler_settings', sa.Column('last_run', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler_settings', 'last_run')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index('idx_activity_logs_type', table_name='activity_logs')
    op.drop_index('idx_activity_logs_id', table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
