"""sensor_logs

Revision ID: c1c5697e9d49
Revises: 24e806715c23
Create Date: 2026-05-12 22:32:41.318780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c5697e9d49'
down_revision: Union[str, Sequence[str], None] = '24e806715c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_type', sa.Enum('temperature', 'turbidity', 'ph', 'tds', 'ammonium', 'do', name='sensor_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('NORMAL', 'WARNING', 'DANGER', name='sensor_status_enum'), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sensor_logs_id', 'sensor_logs', ['id'], unique=False)
    op.create_index('idx_sensor_logs_status', 'sensor_logs', ['status'], unique=False)
    op.create_index('idx_sensor_logs_type', 'sensor_logs', ['sensor_type'], unique=False)
    op.create_index(op.f('ix_sensor_logs_id'), 'sensor_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_logs_id'), table_name='sensor_logs')
    op.drop_index('idx_sensor_logs_type', table_name='sensor_logs')
    op.drop_index('idx_sensor_logs_status', table_name='sensor_logs')
    op.drop_index('idx_sensor_logs_id', table_name='sensor_logs')
    op.drop_table('sensor_logs')
    # ### end Alembic commands ###
