"""migration table

Revision ID: fb3179d6205f
Revises: 
Create Date: 2026-01-11 23:12:36.437140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb3179d6205f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calibration_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_settings_calibration_type'), 'calibration_settings', ['calibration_type'], unique=True)
    op.create_index(op.f('ix_calibration_settings_id'), 'calibration_settings', ['id'], unique=False)
    op.create_table('crab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('group_by', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_crab_id'), 'crab', ['id'], unique=False)
    op.create_table('crab_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crab_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('prediction', 'actual', name='crab_logs_enum'), nullable=False),
    sa.Column('width', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crab_logs_id', 'crab_logs', ['id'], unique=False)
    op.create_index('idx_crab_logs_type', 'crab_logs', ['type'], unique=False)
    op.create_index(op.f('ix_crab_logs_crab_id'), 'crab_logs', ['crab_id'], unique=False)
    op.create_index(op.f('ix_crab_logs_id'), 'crab_logs', ['id'], unique=False)
    op.create_table('scheduler_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('feeding', 'valve', name='scheduler_type_enum'), nullable=False),
    sa.Column('scheduler_type', sa.Enum('daily', 'weekly', 'monthly', 'custom', name='scheduler_enum'), nullable=False),
    sa.Column('hour', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('seconds', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_settings_id'), 'scheduler_settings', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('pin', sa.String(length=100), nullable=False),
    sa.Column('roles', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scheduler_settings_id'), table_name='scheduler_settings')
    op.drop_table('scheduler_settings')
    op.drop_index(op.f('ix_crab_logs_id'), table_name='crab_logs')
    op.drop_index(op.f('ix_crab_logs_crab_id'), table_name='crab_logs')
    op.drop_index('idx_crab_logs_type', table_name='crab_logs')
    op.drop_index('idx_crab_logs_id', table_name='crab_logs')
    op.drop_table('crab_logs')
    op.drop_index(op.f('ix_crab_id'), table_name='crab')
    op.drop_table('crab')
    op.drop_index(op.f('ix_calibration_settings_id'), table_name='calibration_settings')
    op.drop_index(op.f('ix_calibration_settings_calibration_type'), table_name='calibration_settings')
    op.drop_table('calibration_settings')
    # ### end Alembic commands ###
